# Generated by Django 3.2.15 on 2022-09-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='cold',
            field=models.TextField(blank=True, null=True),
        ),
    ]
