# Generated by Django 3.2.15 on 2022-09-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
