# Generated by Django 3.2.15 on 2022-10-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_coffee_cold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='cold',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='size',
            field=models.BooleanField(null=True),
        ),
    ]
