# Generated by Django 3.2.15 on 2022-10-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20221002_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='cold',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='info',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='price',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='size',
        ),
    ]
