# Generated by Django 3.2.15 on 2022-09-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20220922_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='img',
        ),
    ]
