# Generated by Django 3.2.15 on 2022-10-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
