# Generated by Django 3.2.15 on 2022-09-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_remove_coffee_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='cold',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='cups',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='size',
            field=models.TextField(null=True),
        ),
    ]
