# Generated by Django 3.2.15 on 2022-09-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20220922_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='cups',
            field=models.IntegerField(null=True),
        ),
    ]
