# Generated by Django 3.2.15 on 2022-10-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20221020_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone_number',
            new_name='id',
        ),
    ]
